### ISSUE TITLE
Cannot save RefundReceipt (unsupported property)

### ISSUE THREAD

**Issue by bendavis78** [ej2/python-quickbooks#164] opened 2019-09-10 17:24 UTC
When trying to update an existing `RefundReceipt` (retrieved using `.query()`), I get an error saying "Request has invalid or unsupported property". Although it does not say which property is the offending one.

Here is the `.to_dict()` of the object I'm trying to save:

```

{'ApplyTaxAfterDiscount': False,
 'Balance': 0,
 'BillAddr': {'City': '***',
  'Country': '',
  'CountrySubDivisionCode': '***',
  'Id': '62',
  'Lat': '',
  'Line1': '***, Apt 234',
  'Line2': '',
  'Line3': '',
  'Line4': '',
  'Line5': '',
  'Long': '',
  'Note': '',
  'PostalCode': '75208'},
 'BillEmail': {'Address': '*******@yahoo.com'},
 'CheckPayment': '',
 'ClassRef': None,
 'CreditCardPayment': '',
 'CurrencyRef': {'name': 'United States Dollar', 'type': '', 'value': 'USD'},
 'CustomField': [],
 'CustomerMemo': '',
 'CustomerRef': {'name': '***********', 'type': '', 'value': '165'},
 'DepartmentRef': None,
 'DepositToAccountRef': {'name': 'Online Merchant Accounts:Braintree',
  'type': '',
  'value': '42'},
 'DocNumber': 'rm4dvmfm',
 'ExchangeRate': 1,
 'GlobalTaxCalculation': 'TaxExcluded',
 'Id': '936',
 'Line': [{'Amount': 50.0,
   'CustomField': [],
   'Description': 'Program fee refund',
   'DetailType': 'SalesItemLineDetail',
   'Id': '1',
   'LineNum': 1,
   'LinkedTxn': [],
   'SalesItemLineDetail': {'ItemRef': {'name': 'Program Service Fee',
     'value': '3'},
    'TaxCodeRef': {'value': 'NON'}}},
  {'Amount': 50.0,
   'CustomField': [],
   'Description': None,
   'DetailType': 'SubTotalLineDetail',
   'Id': None,
   'LineNum': 0,
   'LinkedTxn': [],
   'SubTotalLineDetail': {}}],
 'LinkedTxn': [],
 'MetaData': {'CreateTime': '2018-12-21T15:29:46-08:00',
  'LastUpdatedTime': '2018-12-21T15:29:46-08:00'},
 'PaymentMethodRef': None,
 'PaymentRefNum': '',
 'PaymentType': '',
 'PrintStatus': 'NotSet',
 'PrivateNote': '',
 'ShipAddr': None,
 'SyncToken': '0',
 'TotalAmt': 50.0,
 'TxnDate': '2018-09-28',
 'TxnSource': None,
 'TxnTaxDetail': None,
 'domain': 'QBO',
 'sparse': False
}
```

**Comment by roseundy** [comment] 2020-02-08 06:08
I have also run into this bug. The problem is with the following attributes (properties):
CustomField
CustomerMemo
CheckPayment
CreditCardPayment
PaymentType

A work-around is to delete those attributes from the refundreceipt object before calling the save function.

**Comment by ej2** [comment] 2020-08-24 18:56
I think I found the problem. This will be fixed in the next release.

**Closed by ej2** 2020-08-24 18:56 UTC

**Comment by gfleetwood** [comment] 2024-10-24 12:13
Hi @ej2, sorry for surfacing this old issue, but I'm having a similar problem now trying to create refund receipts. What was the issue that was fixed?

**Comment by gfleetwood** [comment] 2024-10-24 23:50
@ej2 It looks like Quickbooks Refund Receipts no longer support the PaymentType attribute. Once I ran this line it started working:

```delattr(refund_receipt, 'PaymentType')```

**Comment by digitaltommy** [comment] 2025-11-25 22:43
> [@ej2](https://github.com/ej2) It looks like Quickbooks Refund Receipts no longer supports the PaymentType attribute. Once I ran this line it started working:
> 
> `delattr(refund_receipt, 'PaymentType')`

This was my fix after 3 hours of head scratching. Many thanks @gfleetwood.
